kind: pipeline
name: default

steps:
- name: frontend
  image: adoptopenjdk/maven-openjdk11
  commands:
  - mvn package -DskipTests=false
- name: docker  
  image: plugins/docker
  settings:
    repo: toaler/web-tech-stack
    tags:
     - '0.1'
    username:
      from_secret: dockerhub_username
    password:
      from_secret: dockerhub_password
